"use server";

import { ReportCategoryMain, ReportStatus } from "@service/report/shared";
import z from "zod";
import { getUser } from "@/lib/auth/server";
import { safeAction } from "@/lib/protocol/server-action";

// Mock 데이터
const mockReports = [
  {
    id: "550e8400-e29b-41d4-a716-446655440001",
    reportedAt: new Date("2026-01-04T10:30:00"),
    reporterUserId: "user-reporter-001",
    reporterName: "김철수",
    reporterEmail: "kim@example.com",
    targetType: "WORKBOOK",
    targetId: "workbook-123",
    targetOwnerName: "박선생",
    targetOwnerEmail: "parkteacher@example.com",
    categoryMain: ReportCategoryMain.ERROR,
    categoryDetail: "ERROR_ANSWER",
    detailText:
      "3번 문제의 정답이 틀렸습니다. 해설에서는 25라고 하는데 계산하면 35가 나옵니다.",
    status: ReportStatus.RECEIVED,
    processorUserId: null,
    processedAt: null,
    processingNote: null,
    reportCount: 7,
    isPriority: true,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440002",
    reportedAt: new Date("2026-01-04T09:15:00"),
    reporterUserId: "user-reporter-002",
    reporterName: "이영희",
    reporterEmail: "lee@example.com",
    targetType: "BLOCK",
    targetId: "block-456",
    targetOwnerName: "최교수",
    targetOwnerEmail: "choiprof@example.com",
    categoryMain: ReportCategoryMain.VIOLATION,
    categoryDetail: "VIOL_COPYRIGHT",
    detailText: "이 문제는 다른 출판사 교재에서 무단 복제한 것 같습니다.",
    status: ReportStatus.IN_REVIEW,
    processorUserId: "admin-001",
    processedAt: null,
    processingNote: null,
    reportCount: 12,
    isPriority: true,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440003",
    reportedAt: new Date("2026-01-03T14:20:00"),
    reporterUserId: "user-reporter-003",
    reporterName: "박민수",
    reporterEmail: "park@example.com",
    targetType: "WORKBOOK",
    targetId: "workbook-789",
    targetOwnerName: "김강사",
    targetOwnerEmail: "kimlecturer@example.com",
    categoryMain: ReportCategoryMain.ERROR,
    categoryDetail: "ERROR_TYPO",
    detailText: "페이지 전체적으로 오타가 많습니다.",
    status: ReportStatus.RECEIVED,
    processorUserId: null,
    processedAt: null,
    processingNote: null,
    reportCount: 2,
    isPriority: false,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440004",
    reportedAt: new Date("2026-01-03T11:00:00"),
    reporterUserId: "user-reporter-004",
    reporterName: "정수현",
    reporterEmail: "jung@example.com",
    targetType: "OTHER",
    targetId: "system-issue-01",
    targetOwnerName: "시스템",
    targetOwnerEmail: "system@solves.com",
    categoryMain: ReportCategoryMain.OTHER,
    categoryDetail: "OTHER_SYSTEM",
    detailText: "메인 페이지에서 버튼이 제대로 작동하지 않습니다.",
    status: ReportStatus.RESOLVED,
    processorUserId: "admin-002",
    processedAt: new Date("2026-01-03T15:30:00"),
    processingNote: "시스템 업데이트로 해결되었습니다.",
    reportCount: 1,
    isPriority: false,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440005",
    reportedAt: new Date("2026-01-02T16:45:00"),
    reporterUserId: "user-reporter-005",
    reporterName: "최지은",
    reporterEmail: "choi@example.com",
    targetType: "BLOCK",
    targetId: "block-321",
    targetOwnerName: "이튜터",
    targetOwnerEmail: "leetutor@example.com",
    categoryMain: ReportCategoryMain.VIOLATION,
    categoryDetail: "VIOL_TITLE",
    detailText: "부적절한 내용이 포함되어 있습니다.",
    status: ReportStatus.IN_REVIEW,
    processorUserId: "admin-001",
    processedAt: null,
    processingNote: null,
    reportCount: 8,
    isPriority: true,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440006",
    reportedAt: new Date("2026-01-02T08:30:00"),
    reporterUserId: "user-reporter-006",
    reporterName: "강동원",
    reporterEmail: "kang@example.com",
    targetType: "WORKBOOK",
    targetId: "workbook-555",
    targetOwnerName: "정학원",
    targetOwnerEmail: "jungacademy@example.com",
    categoryMain: ReportCategoryMain.ERROR,
    categoryDetail: "ERROR_ANSWER",
    detailText: "LC 파트 오디오 파일이 재생되지 않습니다.",
    status: ReportStatus.REJECTED,
    processorUserId: "admin-003",
    processedAt: new Date("2026-01-02T14:00:00"),
    processingNote: "오디오 파일은 정상 작동 확인됨. 사용자 환경 문제로 추정.",
    reportCount: 1,
    isPriority: false,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440007",
    reportedAt: new Date("2026-01-01T18:20:00"),
    reporterUserId: "user-reporter-007",
    reporterName: "윤서영",
    reporterEmail: "yoon@example.com",
    targetType: "WORKBOOK",
    targetId: "workbook-888",
    targetOwnerName: "한코치",
    targetOwnerEmail: "hancoach@example.com",
    categoryMain: ReportCategoryMain.ERROR,
    categoryDetail: "ERROR_EXPLANATION",
    detailText: "해설이 너무 간략해서 이해하기 어렵습니다.",
    status: ReportStatus.RECEIVED,
    processorUserId: null,
    processedAt: null,
    processingNote: null,
    reportCount: 3,
    isPriority: false,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440008",
    reportedAt: new Date("2026-01-01T15:10:00"),
    reporterUserId: "user-reporter-008",
    reporterName: "한지민",
    reporterEmail: "han@example.com",
    targetType: "BLOCK",
    targetId: "block-777",
    targetOwnerName: "송멘토",
    targetOwnerEmail: "songmentor@example.com",
    categoryMain: ReportCategoryMain.VIOLATION,
    categoryDetail: "VIOL_SPAM",
    detailText: "광고성 내용이 포함되어 있습니다.",
    status: ReportStatus.RESOLVED,
    processorUserId: "admin-002",
    processedAt: new Date("2026-01-01T17:30:00"),
    processingNote: "광고 내용 삭제 처리",
    reportCount: 6,
    isPriority: true,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440009",
    reportedAt: new Date("2025-12-31T22:30:00"),
    reporterUserId: "user-reporter-009",
    reporterName: "송중기",
    reporterEmail: "song@example.com",
    targetType: "WORKBOOK",
    targetId: "workbook-999",
    targetOwnerName: "오강사",
    targetOwnerEmail: "ohlecturer@example.com",
    categoryMain: ReportCategoryMain.ERROR,
    categoryDetail: "ERROR_TYPO",
    detailText: "제목에 오타가 있습니다.",
    status: ReportStatus.RECEIVED,
    processorUserId: null,
    processedAt: null,
    processingNote: null,
    reportCount: 1,
    isPriority: false,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440010",
    reportedAt: new Date("2025-12-31T14:00:00"),
    reporterUserId: "user-reporter-010",
    reporterName: "박보영",
    reporterEmail: "parkbo@example.com",
    targetType: "BLOCK",
    targetId: "block-111",
    targetOwnerName: "임선생",
    targetOwnerEmail: "limteacher@example.com",
    categoryMain: ReportCategoryMain.VIOLATION,
    categoryDetail: "VIOL_PERSONAL_DATA",
    detailText: "개인정보가 노출되어 있습니다.",
    status: ReportStatus.IN_REVIEW,
    processorUserId: "admin-001",
    processedAt: null,
    processingNote: null,
    reportCount: 15,
    isPriority: true,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440011",
    reportedAt: new Date("2025-12-30T10:30:00"),
    reporterUserId: "user-reporter-011",
    reporterName: "전지현",
    reporterEmail: "jun@example.com",
    targetType: "OTHER",
    targetId: "system-issue-02",
    targetOwnerName: "시스템",
    targetOwnerEmail: "system@solves.com",
    categoryMain: ReportCategoryMain.OTHER,
    categoryDetail: "OTHER_FREE",
    detailText: "문제 이미지가 로딩되지 않습니다.",
    status: ReportStatus.RECEIVED,
    processorUserId: null,
    processedAt: null,
    processingNote: null,
    reportCount: 2,
    isPriority: false,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440012",
    reportedAt: new Date("2025-12-30T08:15:00"),
    reporterUserId: "user-reporter-012",
    reporterName: "이정재",
    reporterEmail: "leej@example.com",
    targetType: "WORKBOOK",
    targetId: "workbook-222",
    targetOwnerName: "장교수",
    targetOwnerEmail: "jangprof@example.com",
    categoryMain: ReportCategoryMain.ERROR,
    categoryDetail: "ERROR_ANSWER",
    detailText: "정답이 여러 개 가능한데 하나만 정답 처리됩니다.",
    status: ReportStatus.RESOLVED,
    processorUserId: "admin-003",
    processedAt: new Date("2025-12-30T12:00:00"),
    processingNote: "복수 정답 처리 완료",
    reportCount: 4,
    isPriority: false,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440013",
    reportedAt: new Date("2025-12-29T19:45:00"),
    reporterUserId: "user-reporter-013",
    reporterName: "김태희",
    reporterEmail: "kimt@example.com",
    targetType: "BLOCK",
    targetId: "block-333",
    targetOwnerName: "홍튜터",
    targetOwnerEmail: "hongtutor@example.com",
    categoryMain: ReportCategoryMain.VIOLATION,
    categoryDetail: "VIOL_GUIDELINE",
    detailText: "커뮤니티 가이드라인 위반 내용이 있습니다.",
    status: ReportStatus.REJECTED,
    processorUserId: "admin-002",
    processedAt: new Date("2025-12-29T21:00:00"),
    processingNote: "가이드라인 위반 사항 없음",
    reportCount: 1,
    isPriority: false,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440014",
    reportedAt: new Date("2025-12-29T16:20:00"),
    reporterUserId: "user-reporter-014",
    reporterName: "현빈",
    reporterEmail: "hyun@example.com",
    targetType: "WORKBOOK",
    targetId: "workbook-444",
    targetOwnerName: "서코치",
    targetOwnerEmail: "seocoach@example.com",
    categoryMain: ReportCategoryMain.ERROR,
    categoryDetail: "ERROR_TYPO",
    detailText: "문제 전체에 오타가 많습니다.",
    status: ReportStatus.IN_REVIEW,
    processorUserId: "admin-001",
    processedAt: null,
    processingNote: null,
    reportCount: 5,
    isPriority: true,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440015",
    reportedAt: new Date("2025-12-29T12:00:00"),
    reporterUserId: "user-reporter-015",
    reporterName: "손예진",
    reporterEmail: "sony@example.com",
    targetType: "BLOCK",
    targetId: "block-555",
    targetOwnerName: "권강사",
    targetOwnerEmail: "kwonlecturer@example.com",
    categoryMain: ReportCategoryMain.VIOLATION,
    categoryDetail: "VIOL_COPYRIGHT",
    detailText: "저작권 침해 의심 내용입니다.",
    status: ReportStatus.RECEIVED,
    processorUserId: null,
    processedAt: null,
    processingNote: null,
    reportCount: 9,
    isPriority: true,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440016",
    reportedAt: new Date("2025-12-28T20:30:00"),
    reporterUserId: "user-reporter-016",
    reporterName: "유재석",
    reporterEmail: "yoo@example.com",
    targetType: "WORKBOOK",
    targetId: "workbook-666",
    targetOwnerName: "신선생",
    targetOwnerEmail: "shinteacher@example.com",
    categoryMain: ReportCategoryMain.ERROR,
    categoryDetail: "ERROR_EXPLANATION",
    detailText: "해설에 오류가 있습니다.",
    status: ReportStatus.RECEIVED,
    processorUserId: null,
    processedAt: null,
    processingNote: null,
    reportCount: 2,
    isPriority: false,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440017",
    reportedAt: new Date("2025-12-28T17:15:00"),
    reporterUserId: "user-reporter-017",
    reporterName: "박나래",
    reporterEmail: "parkn@example.com",
    targetType: "OTHER",
    targetId: "system-issue-03",
    targetOwnerName: "시스템",
    targetOwnerEmail: "system@solves.com",
    categoryMain: ReportCategoryMain.OTHER,
    categoryDetail: "OTHER_SYSTEM",
    detailText: "페이지가 느리게 로딩됩니다.",
    status: ReportStatus.RESOLVED,
    processorUserId: "admin-003",
    processedAt: new Date("2025-12-28T19:00:00"),
    processingNote: "서버 최적화 완료",
    reportCount: 3,
    isPriority: false,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440018",
    reportedAt: new Date("2025-12-28T13:45:00"),
    reporterUserId: "user-reporter-018",
    reporterName: "이광수",
    reporterEmail: "leek@example.com",
    targetType: "BLOCK",
    targetId: "block-666",
    targetOwnerName: "안멘토",
    targetOwnerEmail: "ahnmentor@example.com",
    categoryMain: ReportCategoryMain.VIOLATION,
    categoryDetail: "VIOL_TITLE",
    detailText: "제목이 부적절합니다.",
    status: ReportStatus.IN_REVIEW,
    processorUserId: "admin-002",
    processedAt: null,
    processingNote: null,
    reportCount: 7,
    isPriority: true,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440019",
    reportedAt: new Date("2025-12-27T22:00:00"),
    reporterUserId: "user-reporter-019",
    reporterName: "김종국",
    reporterEmail: "kimj@example.com",
    targetType: "WORKBOOK",
    targetId: "workbook-777",
    targetOwnerName: "문학원",
    targetOwnerEmail: "moonacademy@example.com",
    categoryMain: ReportCategoryMain.ERROR,
    categoryDetail: "ERROR_ANSWER",
    detailText: "보기 선택지가 잘못되었습니다.",
    status: ReportStatus.RECEIVED,
    processorUserId: null,
    processedAt: null,
    processingNote: null,
    reportCount: 1,
    isPriority: false,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440020",
    reportedAt: new Date("2025-12-27T18:30:00"),
    reporterUserId: "user-reporter-020",
    reporterName: "송지효",
    reporterEmail: "songj@example.com",
    targetType: "BLOCK",
    targetId: "block-888",
    targetOwnerName: "류교수",
    targetOwnerEmail: "ryuprof@example.com",
    categoryMain: ReportCategoryMain.VIOLATION,
    categoryDetail: "VIOL_SPAM",
    detailText: "스팸 내용이 있습니다.",
    status: ReportStatus.REJECTED,
    processorUserId: "admin-001",
    processedAt: new Date("2025-12-27T20:00:00"),
    processingNote: "정상 내용으로 확인됨",
    reportCount: 1,
    isPriority: false,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440021",
    reportedAt: new Date("2025-12-27T14:00:00"),
    reporterUserId: "user-reporter-021",
    reporterName: "하하",
    reporterEmail: "haha@example.com",
    targetType: "WORKBOOK",
    targetId: "workbook-100",
    targetOwnerName: "배튜터",
    targetOwnerEmail: "baetutor@example.com",
    categoryMain: ReportCategoryMain.ERROR,
    categoryDetail: "ERROR_TYPO",
    detailText: "문법 오류가 있습니다.",
    status: ReportStatus.RESOLVED,
    processorUserId: "admin-003",
    processedAt: new Date("2025-12-27T16:30:00"),
    processingNote: "문법 오류 수정 완료",
    reportCount: 6,
    isPriority: true,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440022",
    reportedAt: new Date("2025-12-26T21:30:00"),
    reporterUserId: "user-reporter-022",
    reporterName: "지석진",
    reporterEmail: "jis@example.com",
    targetType: "OTHER",
    targetId: "system-issue-04",
    targetOwnerName: "시스템",
    targetOwnerEmail: "system@solves.com",
    categoryMain: ReportCategoryMain.OTHER,
    categoryDetail: "OTHER_FREE",
    detailText: "앱이 자주 멈춥니다.",
    status: ReportStatus.RECEIVED,
    processorUserId: null,
    processedAt: null,
    processingNote: null,
    reportCount: 4,
    isPriority: false,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440023",
    reportedAt: new Date("2025-12-26T16:45:00"),
    reporterUserId: "user-reporter-023",
    reporterName: "양세찬",
    reporterEmail: "yang@example.com",
    targetType: "BLOCK",
    targetId: "block-200",
    targetOwnerName: "표코치",
    targetOwnerEmail: "pyocoach@example.com",
    categoryMain: ReportCategoryMain.VIOLATION,
    categoryDetail: "VIOL_PERSONAL_DATA",
    detailText: "개인정보가 포함되어 있습니다.",
    status: ReportStatus.IN_REVIEW,
    processorUserId: "admin-002",
    processedAt: null,
    processingNote: null,
    reportCount: 11,
    isPriority: true,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440024",
    reportedAt: new Date("2025-12-26T12:15:00"),
    reporterUserId: "user-reporter-024",
    reporterName: "전소민",
    reporterEmail: "jeons@example.com",
    targetType: "WORKBOOK",
    targetId: "workbook-300",
    targetOwnerName: "고선생",
    targetOwnerEmail: "goteacher@example.com",
    categoryMain: ReportCategoryMain.ERROR,
    categoryDetail: "ERROR_EXPLANATION",
    detailText: "설명이 부족합니다.",
    status: ReportStatus.RECEIVED,
    processorUserId: null,
    processedAt: null,
    processingNote: null,
    reportCount: 2,
    isPriority: false,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440025",
    reportedAt: new Date("2025-12-25T23:00:00"),
    reporterUserId: "user-reporter-025",
    reporterName: "김민아",
    reporterEmail: "kimm@example.com",
    targetType: "BLOCK",
    targetId: "block-300",
    targetOwnerName: "남강사",
    targetOwnerEmail: "namlecturer@example.com",
    categoryMain: ReportCategoryMain.VIOLATION,
    categoryDetail: "VIOL_GUIDELINE",
    detailText: "가이드라인 위반 내용입니다.",
    status: ReportStatus.RESOLVED,
    processorUserId: "admin-001",
    processedAt: new Date("2025-12-26T10:00:00"),
    processingNote: "위반 내용 삭제 완료",
    reportCount: 8,
    isPriority: true,
  },
];

export const getReports = safeAction(
  z.object({
    page: z.number().optional().default(1),
    limit: z.number().optional().default(10),
    categoryMain: z
      .enum([
        ReportCategoryMain.ERROR,
        ReportCategoryMain.VIOLATION,
        ReportCategoryMain.OTHER,
      ])
      .optional(),
    status: z
      .enum([
        ReportStatus.RECEIVED,
        ReportStatus.IN_REVIEW,
        ReportStatus.RESOLVED,
        ReportStatus.REJECTED,
      ])
      .optional(),
    search: z.string().optional(),
    priorityOnly: z.boolean().optional().default(false),
  }),
  async ({ page, limit, categoryMain, status, search, priorityOnly }) => {
    await getUser(); // 인증 확인

    // 필터링
    let filtered = [...mockReports];

    if (categoryMain) {
      filtered = filtered.filter((r) => r.categoryMain === categoryMain);
    }

    if (status) {
      filtered = filtered.filter((r) => r.status === status);
    }

    if (search) {
      const query = search.toLowerCase();
      filtered = filtered.filter(
        (r) =>
          r.detailText?.toLowerCase().includes(query) ||
          r.targetId.toLowerCase().includes(query),
      );
    }

    if (priorityOnly) {
      filtered = filtered.filter((r) => r.isPriority);
    }

    // 통계 계산
    const priorityCount = mockReports.filter(
      (r) =>
        r.isPriority &&
        (r.status === ReportStatus.RECEIVED ||
          r.status === ReportStatus.IN_REVIEW),
    ).length;

    const pendingCount = mockReports.filter(
      (r) =>
        r.status === ReportStatus.RECEIVED ||
        r.status === ReportStatus.IN_REVIEW,
    ).length;

    const errorCount = mockReports.filter(
      (r) => r.categoryMain === ReportCategoryMain.ERROR,
    ).length;

    const violationCount = mockReports.filter(
      (r) => r.categoryMain === ReportCategoryMain.VIOLATION,
    ).length;

    // 페이지네이션
    const totalCount = filtered.length;
    const totalPages = Math.ceil(totalCount / limit);
    const offset = (page - 1) * limit;
    const paginatedReports = filtered.slice(offset, offset + limit);

    return {
      reports: paginatedReports.map((report) => ({
        ...report,
        reportedAt: report.reportedAt.toISOString(),
        processedAt: report.processedAt?.toISOString() ?? null,
      })),
      totalCount,
      page,
      limit,
      totalPages,
      stats: {
        priorityCount,
        pendingCount,
        errorCount,
        violationCount,
      },
    };
  },
);
