name: Lint & Type Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint-and-type-check:
    name: Run Lint & Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: pnpm i

      - name: Run Lint
        run: pnpm lint

      - name: Run Type Check
        run: pnpm check-types
